# Change these first
owner: Milwaukee-Bucks # Your GitHub organization or username, where this repository lives
repo: uptime-monitor # The name of this repository

sites:
  - name: Milwaukee Bucks Main Website
    url: https://www.nba.com/bucks
    expectedStatusCodes:
      - 200
  - name: bucks.com Redirect
    url: https://bucks.com
    expectedStatusCodes:
      - 200
      - 301
      - 302
  - name: Deer District
    url: https://deerdistrict.com
    __dangerous__body_down_if_text_missing: 'Deer District'
  - name: The MECCA
    url: https://themeccamke.com
    __dangerous__body_down_if_text_missing: '1134 N. Vel R. Phillips Ave. Milwaukee, WI 53203'

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /uptime-monitor
  logoUrl: https://avatars.githubusercontent.com/u/123599855?s=400&u=eaeb2b292d741334cbf7ed2ad2d37c2545222ca4&v=4
  name: Upptime
  introTitle: "Milwaukee Bucks Digital Platforms Monitoring"
  introMessage: Status of Milwaukee Bucks digital Platforms
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
